version: '3'
services:
  ganache:
    image: trufflesuite/ganache-cli:latest
    container_name: ganache
    networks:
      - backend
    volumes:
      - chaindata:/var/www/app/chaindata
    command: --networkId 3 -m 'grass whip zero open purse liar arrive camp mosquito claw tool actress' --db chaindata
    ports:
      - "8545:8545"


volumes:
  chaindata:

networks:
  backend:
    external: true
