version: '3'
services:
  mongodb:
    image: mongo:4.2
    container_name: mongo
    restart: always
    volumes:
      - data:/etc/mongo:z
    networks:
      - backend
    ports:
      - "27017:27017"

volumes:
  data:

networks:
  backend:
    external: true
