version: '3'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - nginx-certs:/etc/nginx/certs
      - nginx-html:/usr/share/nginx/html
      - nginx-vhostd:/etc/nginx/vhost.d
    ports:
      - "80:80"
      - "443:443"
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    depends_on:
      - "nginx-proxy"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - nginx-certs:/etc/nginx/certs
      - nginx-html:/usr/share/nginx/html
      - nginx-vhostd:/etc/nginx/vhost.d
      - /etc/acme.sh
    environment:
      DEFAULT_EMAIL: ali.sepehri.kh@gmail.com

volumes:
  nginx-certs:
  nginx-html:
  nginx-vhostd:
