version: '3.7'
services:
  api:
    image: registry.gitlab.com/alisepehri/proof-of-prediction/api:$CI_COMMIT_REF_SLUG
    entrypoint:
      - "/var/www/app/docker/entrypoints/start.sh"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000"]
      interval: 5s
      timeout: 10s
      retries: 5
    deploy:
      update_config:
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      DATABASE_CONNECTION_STRING: mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongodb/proofOfPrediction_db?authSource=admin
      ETHEREUM_APP_ACCOUNT_ID: ${ETHEREUM_APP_ACCOUNT_ID}
      ETHEREUM_APP_ACCOUNT_PRIVATE_KEY: ${ETHEREUM_APP_ACCOUNT_PRIVATE_KEY}
      ETHEREUM_NETWORK: ${ETHEREUM_NETWORK}
      PREDICTION_HASH_CONTRACT_ADDRESS: ${PREDICTION_HASH_CONTRACT_ADDRESS}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      PORT: 4000
      VIRTUAL_HOST: api.proofiction.site
      VIRTUAL_PORT: 4000
      LETSENCRYPT_HOST: api.proofiction.site
    ports:
      - "4000:4000"
