version: '3'
services:
  mongodb:
    image: mongo:4.2
    volumes:
      - mongo-data:/data/db:z
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}

volumes:
  mongo-data:
