version: '3'
services:
  client:
    image: registry.proofication.com/client:development
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: client
    networks:
      - backend
    entrypoint:
      - "/var/www/app/docker/entrypoints/start.sh"
    ports:
      - "3000:3000"

networks:
  backend:
    external: true
